spring.application.name=NotesApp
spring.datasource.url=jdbc:mysql://localhost:3306/NotesDB
spring.datasource.username=root
spring.datasource.password=pandey13
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

jwt.secret=XxsHhRm46OHl4SmUOIJZIb7CfmqcWah9CK4YwtEPhC6
jwt.expiration-ms=3600000
